### ISSUE TITLE
about the QR code

### ISSUE THREAD

**Issue by ZacharyWang-007** [openmedlab/SAM-Med2D#1]
Dear all, thanks for the excellent job. I would like to apply your pre-trained model on my own datasets. However, you didn't provide details in terms of window size, window level, and dicm to rgb procssing code. 

Could you please update the QR code and I can ask some details in the group.

Best regards

**Comment by Ziyan-Huang** [comment]
Thank you for your kind words and interest in SAM-Med2D. We have updated the QR code as requested. Due to the chat group exceeding 200 members, we kindly ask you to add GV Assistant (GV 小助手) as a contact, and we will facilitate your invitation to the group for further discussions.
